name: Minify
on:
# Disable the following line if you don't want the Action to run on PRs.
#- pull_request
# Enable the following line if you want the Action to run on regular pushes.
- push

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@master

      # Auto commits minified files to the repository
      # Ignore it if you don't want to commit the files to the repository 
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
