name: SVGOptimizer
on:
# Disable the following line if you don't want the Action to run on PRs.
- pull_request
# Enable the following line if you want the Action to run on regular pushes.
#- push

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: ericcornelissen/svgo-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
